/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ToolSummary } from './tool-summary';

/**
 * Properties for the `agent.tools.available` event.
 */
export interface AgentToolsAvailableProps {
    /**
     * Effective model-callable tools exposed to the stage session.
     */
    'tools': Array<ToolSummary>;
    'visit': number;
}
