/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Properties for every `agent.*` and `todo.*` event: the stage that owns the session plus the coding agent\'s own event envelope. `event` is the externally tagged coding event, `{\"ToolCallStarted\": {...}}` or a bare `\"SessionEnded\"`. Variant names are permanent API; their payloads are documented by the pebble coding agent.
 */
export interface AgentEventProps {
    /**
     * Graph node id of the stage that owns the session.
     */
    'stage': string;
    'visit': number;
    /**
     * Position in the session\'s event stream.
     */
    'seq'?: number;
    /**
     * The event stream this event belongs to.
     */
    'stream_id'?: string;
    'event': any;
    'timestamp': string;
    'session_id': string;
    'parent_session_id'?: string | null;
    'tool_call_id'?: string | null;
}
