/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ExternalAgentHarness } from './external-agent-harness';

/**
 * Plane ticket polling trigger.
 */
export interface AutomationPlaneTrigger {
    'id': string;
    'type': AutomationPlaneTriggerTypeEnum;
    'enabled': boolean;
    /**
     * Plane project ID.
     */
    'project_id': string;
    /**
     * Plane Ready state ID.
     */
    'ready_state_id': string;
    /**
     * Plane In Progress state ID.
     */
    'in_progress_state_id': string;
    /**
     * Plane Done state ID.
     */
    'done_state_id': string;
    /**
     * Plane Cancelled state ID.
     */
    'cancelled_state_id': string;
    /**
     * Optional failure label ID applied after retries are exhausted.
     */
    'failure_label_id'?: string | null;
    'default_harness': ExternalAgentHarness;
    /**
     * Optional label ID selecting Codex harness.
     */
    'codex_label_id'?: string | null;
    /**
     * Optional label ID selecting OMP harness.
     */
    'omp_label_id'?: string | null;
    'poll_interval_seconds'?: number;
    'max_concurrency'?: number;
    'max_retries'?: number;
}

export const AutomationPlaneTriggerTypeEnum = {
    PLANE: 'plane'
} as const;

export type AutomationPlaneTriggerTypeEnum = typeof AutomationPlaneTriggerTypeEnum[keyof typeof AutomationPlaneTriggerTypeEnum];
