/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AutomationGitWorkflowSource } from './automation-git-workflow-source';
// May contain unused imports in some cases
// @ts-ignore
import type { AutomationTrigger } from './automation-trigger';
// May contain unused imports in some cases
// @ts-ignore
import type { RunTarget } from './run-target';

/**
 * Public automation definition.
 */
export interface Automation {
    'id': string;
    /**
     * Stable revision used with `If-Match` for optimistic concurrency.
     */
    'revision': string;
    'name': string;
    'description': string | null;
    /**
     * Server-managed Docker or Daytona environment selected when the automation fires. Null only for an incomplete definition migrated from a release that predated environment selection.
     */
    'environment_id': string | null;
    /**
     * Most recent scheduled-run failure, cleared after a scheduled run is queued successfully.
     */
    'last_error': string | null;
    'target': RunTarget;
    /**
     * Workflow slug or path resolved in the run-target checkout when `workflow_source` is omitted, or in the explicit workflow-source checkout when present.
     */
    'workflow': string;
    'workflow_source'?: AutomationGitWorkflowSource;
    'triggers': Array<AutomationTrigger>;
}
