/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BugsinkProjectSettings } from './bugsink-project-settings';

export interface BugsinkIntegrationSettings {
    'enabled': boolean;
    'dispatch_enabled': boolean;
    'origin': string | null;
    /**
     * Vault entry name for the Bugsink API credential, never its value.
     */
    'api_token_secret': string | null;
    'projects': Array<BugsinkProjectSettings>;
}
