/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContextWindowBreakdownItem } from './context-window-breakdown-item';
// May contain unused imports in some cases
// @ts-ignore
import type { ContextWindowCountMethod } from './context-window-count-method';
// May contain unused imports in some cases
// @ts-ignore
import type { ContextWindowStaleness } from './context-window-staleness';
// May contain unused imports in some cases
// @ts-ignore
import type { ContextWindowWarning } from './context-window-warning';

/**
 * Durable content-free context-window snapshot recorded by the coding agent.
 */
export interface ContextWindowSnapshot {
    'provider': string;
    'model': string;
    'context_window_tokens': number;
    'input_tokens': number;
    'usage_percent': number;
    'count_method': ContextWindowCountMethod;
    'staleness': ContextWindowStaleness;
    'generated_at': string;
    /**
     * Sequence of the agent event this snapshot was taken at, when known.
     */
    'event_seq'?: number | null;
    'breakdown': Array<ContextWindowBreakdownItem>;
    'warnings': Array<ContextWindowWarning>;
}
