/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Freshness of the returned context-window data.
 */

export const ContextWindowStaleness = {
    LIVE: 'live',
    STORED: 'stored',
    UNAVAILABLE: 'unavailable'
} as const;

export type ContextWindowStaleness = typeof ContextWindowStaleness[keyof typeof ContextWindowStaleness];
