/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Category of model-visible input/context tokens.
 */

export const ContextWindowCategory = {
    SYSTEM_PROMPT: 'system_prompt',
    TOOLS: 'tools',
    MCP_TOOLS: 'mcp_tools',
    SKILLS: 'skills',
    MEMORY: 'memory',
    CONVERSATION: 'conversation',
    OTHER: 'other'
} as const;

export type ContextWindowCategory = typeof ContextWindowCategory[keyof typeof ContextWindowCategory];
