/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GitContext } from './git-context';
// May contain unused imports in some cases
// @ts-ignore
import type { ManifestConfig } from './manifest-config';
// May contain unused imports in some cases
// @ts-ignore
import type { ManifestWorkflow } from './manifest-workflow';
// May contain unused imports in some cases
// @ts-ignore
import type { RunIntent } from './run-intent';
// May contain unused imports in some cases
// @ts-ignore
import type { RunIntentArgs } from './run-intent-args';
// May contain unused imports in some cases
// @ts-ignore
import type { RunManifest } from './run-manifest';
// May contain unused imports in some cases
// @ts-ignore
import type { RunTarget } from './run-target';

/**
 * @type CreateRunRequest
 * Transitional create body used while callers migrate independently from self-contained manifests to immutable workflow-version intents.
 */
export type CreateRunRequest = RunIntent | RunManifest;
