/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request body for adding a global automation to a project.
 */
export interface CreateProjectAutomationRequest {
    /**
     * Id of the new project-owned automation instance.
     */
    'id': string;
    'name': string;
    /**
     * Global automation definition marked available to projects.
     */
    'source_automation_id': string;
    /**
     * Revision of the source definition the caller selected.
     */
    'source_revision': string;
    /**
     * Server-managed environment for the project instance.
     */
    'environment_id': string;
    'description'?: string | null;
}
