/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request body for connecting an existing GitHub repository.
 */
export interface CreateProjectRequest {
    'id': string;
    'name': string;
    /**
     * Existing GitHub `owner/repo` slug. The server re-reads its identity.
     */
    'repository': string;
}
