/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EnvironmentImageSettings } from './environment-image-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { EnvironmentLifecycleSettings } from './environment-lifecycle-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { EnvironmentNetworkSettings } from './environment-network-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { EnvironmentResourcesSettings } from './environment-resources-settings';

export interface EnvironmentSettings {
    /**
     * Sandbox provider kind. `local`, `docker`, and `daytona` are bundled with the server; any other value names a sandbox-driver plugin configured under `server.sandbox.providers.<kind>`.
     */
    'provider': string;
    /**
     * Local-provider command working directory for this environment. Docker and Daytona ignore this value.
     */
    'cwd'?: string | null;
    'image': EnvironmentImageSettings;
    'resources': EnvironmentResourcesSettings;
    'network': EnvironmentNetworkSettings;
    'lifecycle': EnvironmentLifecycleSettings;
    'labels': { [key: string]: string; };
    'env': { [key: string]: string; };
}
