/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Selected ACP harness profile for external coding agents.
 */

export const ExternalAgentHarness = {
    CODEX: 'codex',
    OMP: 'omp'
} as const;

export type ExternalAgentHarness = typeof ExternalAgentHarness[keyof typeof ExternalAgentHarness];
