/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Existing directory on the Fabro server, executed in place by a Local environment. The submitted path must be absolute and name an existing directory; Fabro resolves symlinks and persists its canonical UTF-8 path. This target is intended for trusted single-tenant deployments. Docker and Daytona environments always reject it. This target does not add Local Git cloning or Local scratch workspaces. Folder runs execute in place without Fabro Git checkpoints, so fork and rewind are unavailable.
 */
export interface FolderRunTarget {
    'kind': FolderRunTargetKindEnum;
    /**
     * Absolute path on the Fabro server, not on the API caller\'s machine.
     */
    'path': string;
}

export const FolderRunTargetKindEnum = {
    FOLDER: 'folder'
} as const;

export type FolderRunTargetKindEnum = typeof FolderRunTargetKindEnum[keyof typeof FolderRunTargetKindEnum];
