/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GitIdentitySource } from './git-identity-source';

/**
 * The Git author and committer identity a run resolved once and uses for every commit it creates: engine checkpoints, metadata commits, and any commit a workflow command or agent tool runs.
 */
export interface GitIdentity {
    'name': string;
    'email': string;
    'source': GitIdentitySource;
}
