/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Where a run\'s Git author/committer identity came from.
 */

export const GitIdentitySource = {
    EXPLICIT: 'explicit',
    GITHUB_APP: 'github_app',
    GITHUB_PAT: 'github_pat',
    DEFAULT: 'default'
} as const;

export type GitIdentitySource = typeof GitIdentitySource[keyof typeof GitIdentitySource];
