/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GithubRepository } from './github-repository';

/**
 * One page of repositories available to the server.
 */
export interface GithubRepositoryListResponse {
    'data': Array<GithubRepository>;
    /**
     * Opaque server-issued cursor; absent when the list is exhausted.
     */
    'next_cursor'?: string | null;
}
