/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * One repository available to the Fabro server\'s GitHub credentials.
 */
export interface GithubRepository {
    /**
     * Immutable numeric GitHub repository id, decimal-encoded.
     */
    'id': string;
    'full_name': string;
    /**
     * Default branch, null for an empty repository.
     */
    'default_branch': string | null;
    'private': boolean;
    'archived': boolean;
    'disabled': boolean;
}
