/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IntakeReadinessReport } from './intake-readiness-report';

/**
 * Feature-intake capability of one project.
 */
export interface IntakeSetupStatus {
    [key: string]: any;

    /**
     * Registered intake binding id, null when feature intake is not set up.
     */
    'binding': string | null;
    'paused': boolean;
    'setup_required': boolean;
    'readiness'?: IntakeReadinessReport | null;
}
