/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IntakeRunRecord } from './intake-run-record';

/**
 * One feature request in list order.
 */
export interface IntakeInitiativeSummary {
    [key: string]: any;

    'id': string;
    'seq'?: number | null;
    'name': string;
    /**
     * Plane state key, or `unknown` when the issue state is not mapped.
     */
    'state': string;
    'stage': string | null;
    'updated_at'?: string | null;
    'run'?: IntakeRunRecord | null;
}
