/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * One append-only dispatch record. Rows carry the bridge\'s persisted columns; `outcome` is the verified verification result, never optimism.
 */
export interface IntakeRunRecord {
    [key: string]: any;

    'id'?: number;
    'stage': string;
    'event': string;
    'kind': string;
    'outcome': string;
    'node'?: string | null;
    'message': string;
    /**
     * Durable Fabro run id once a run was submitted.
     */
    'run'?: string | null;
    'actor'?: string | null;
    'ts'?: number | null;
}
