/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface IntakeComment {
    [key: string]: any;

    'id'?: string | null;
    'at'?: string | null;
    'who': string;
    'text': string;
    /**
     * True when the comment was written by the automated pipeline.
     */
    'factory': boolean;
}
