/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * One readiness probe result. A flag is only ready when every check passes.
 */
export interface IntakeReadinessCheck {
    [key: string]: any;

    'key': string;
    'outcome': IntakeReadinessCheckOutcomeEnum;
    'message': string;
    'next_action': string;
}

export const IntakeReadinessCheckOutcomeEnum = {
    PASS: 'pass',
    FAIL: 'fail',
    NOT_APPLICABLE: 'not_applicable',
    NOT_CONFIGURED: 'not_configured',
    UNKNOWN: 'unknown'
} as const;

export type IntakeReadinessCheckOutcomeEnum = typeof IntakeReadinessCheckOutcomeEnum[keyof typeof IntakeReadinessCheckOutcomeEnum];
