/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Factory configuration for supervised execution. Secrets are write-only credential references, never values.
 */
export interface IntakeExecutionSetupRequest {
    [key: string]: any;

    'staging_slug'?: string;
    'zone'?: string;
    'commands'?: { [key: string]: string; };
    'staging'?: { [key: string]: any; };
    'adopted'?: { [key: string]: any; };
    /**
     * Provider credential references resolved by the bridge.
     */
    'credentials'?: { [key: string]: string; };
}
