/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface IntakeImportRow {
    [key: string]: any;

    'binding': string;
    'repository'?: string | null;
    'project_id'?: string | null;
    'status': IntakeImportRowStatusEnum;
    'message'?: string | null;
}

export const IntakeImportRowStatusEnum = {
    IMPORTED: 'imported',
    ATTACHED: 'attached',
    CONFLICT: 'conflict',
    ERROR: 'error'
} as const;

export type IntakeImportRowStatusEnum = typeof IntakeImportRowStatusEnum[keyof typeof IntakeImportRowStatusEnum];
