/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Authoring setup. Plane identity is resolved from the server\'s Plane integration; the credential reference stays in the bridge\'s private configuration and is never supplied by the browser.
 */
export interface IntakeSetupRequest {
    /**
     * Existing Plane project the feature requests belong to.
     */
    'plane_project_id': string;
}
