/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Public projection of one registered intake binding.
 */
export interface IntakeBindingSummary {
    [key: string]: any;

    'id': string;
    'name': string;
    'github': string;
    'default_branch': string;
    'plane_project_id'?: string | null;
    'plane_workspace'?: string | null;
    'profile': IntakeBindingSummaryProfileEnum;
    'paused': boolean;
    'execution_configured': boolean;
}

export const IntakeBindingSummaryProfileEnum = {
    INTAKE: 'intake',
    AGENCY_WEB: 'agency-web'
} as const;

export type IntakeBindingSummaryProfileEnum = typeof IntakeBindingSummaryProfileEnum[keyof typeof IntakeBindingSummaryProfileEnum];
