/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Private feature-intake bridge. The bridge listens on a Unix-domain socket owned by the same OS user as the server; no browser traffic reaches it directly.
 */
export interface IntakeIntegrationSettings {
    'enabled': boolean;
    /**
     * Absolute path of the bridge socket, required when enabled.
     */
    'socket': string | null;
}
