/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IntakeComment } from './intake-comment';
// May contain unused imports in some cases
// @ts-ignore
import type { IntakeDocument } from './intake-document';
// May contain unused imports in some cases
// @ts-ignore
import type { IntakeRunRecord } from './intake-run-record';

/**
 * Full feature-request projection: current state, documents, comments, questions, assumptions and verified run history.
 */
export interface IntakeInitiativeDetail {
    [key: string]: any;

    'id': string;
    'seq'?: number | null;
    'name': string;
    'state': string;
    'stage'?: string | null;
    'updated_at'?: string | null;
    'run'?: IntakeRunRecord | null;
    'description'?: string | null;
    'needs_operator'?: boolean;
    /**
     * Draft pull request opened by document authoring, when one exists.
     */
    'pr_url'?: string | null;
    'docs'?: { [key: string]: IntakeDocument; };
    'features'?: { [key: string]: any; } | null;
    /**
     * Machine block from the issue description (commit, stage, PR).
     */
    'block'?: { [key: string]: any; } | null;
    'project'?: { [key: string]: any; } | null;
    'provisioning'?: Array<{ [key: string]: any; }>;
    'comments': Array<IntakeComment>;
    'questions': Array<string>;
    'supuestos': Array<string>;
    'history': Array<IntakeRunRecord>;
}
