/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Result of creating a feature request; `issue` is the created initiative\'s Plane issue id, also returned unchanged when an identical request is retried after a lost response.
 */
export interface IntakeCreateResponse {
    [key: string]: any;

    'ok': boolean;
    'issue'?: string | null;
}
