/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface IntakeStageRequest {
    'stage': IntakeStageRequestStageEnum;
    'supervised'?: boolean;
}

export const IntakeStageRequestStageEnum = {
    PRD: 'prd',
    SPEC: 'spec',
    DESIGN: 'design',
    FREEZE: 'freeze',
    CANCEL: 'cancel',
    EXECUTE: 'execute'
} as const;

export type IntakeStageRequestStageEnum = typeof IntakeStageRequestStageEnum[keyof typeof IntakeStageRequestStageEnum];
