/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The server was ready and then its connection closed during the stage; its tools fail until the session ends.
 */
export interface McpServerStatusDisconnected {
    'kind': McpServerStatusDisconnectedKindEnum;
    /**
     * What closed the connection, as the client observed it.
     */
    'error': string;
}

export const McpServerStatusDisconnectedKindEnum = {
    DISCONNECTED: 'disconnected'
} as const;

export type McpServerStatusDisconnectedKindEnum = typeof McpServerStatusDisconnectedKindEnum[keyof typeof McpServerStatusDisconnectedKindEnum];
