/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const PlaneDispatchStatus = {
    PENDING: 'pending',
    CLAIMED: 'claimed',
    RUNNING: 'running',
    RETRY_PENDING: 'retry_pending',
    SUCCEEDED: 'succeeded',
    FAILED: 'failed',
    CANCELLED: 'cancelled'
} as const;

export type PlaneDispatchStatus = typeof PlaneDispatchStatus[keyof typeof PlaneDispatchStatus];
