/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ExternalAgentHarness } from './external-agent-harness';
// May contain unused imports in some cases
// @ts-ignore
import type { PlaneDispatchStatus } from './plane-dispatch-status';

/**
 * Durable state of a Plane ticket automation dispatch.
 */
export interface PlaneDispatch {
    'automation_id': string;
    'trigger_id': string;
    'issue_id': string;
    'issue_identifier': string;
    'issue_title'?: string | null;
    'issue_url'?: string | null;
    'status': PlaneDispatchStatus;
    'harness': ExternalAgentHarness;
    'attempt': number;
    'run_ids': Array<string>;
    'current_run_id'?: string | null;
    'pull_request_url'?: string | null;
    'last_error'?: string | null;
    'claimed_at'?: string | null;
    'completed_at'?: string | null;
    'created_at': string;
    'updated_at': string;
}
