/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * An existing GitHub repository connected to this Fabro server. `github_repository_id` is the immutable numeric GitHub id as a decimal string; `repository` and `default_branch` are server-read metadata.
 */
export interface Project {
    'id': string;
    /**
     * Stable revision used with `If-Match` for optimistic concurrency.
     */
    'revision': string;
    'name': string;
    /**
     * Immutable numeric GitHub repository id, decimal-encoded.
     */
    'github_repository_id': string;
    /**
     * Canonical `owner/repo` slug as last read from GitHub.
     */
    'repository': string;
    /**
     * Default branch as last read from GitHub.
     */
    'default_branch': string;
    /**
     * Registered feature-intake binding, when feature intake is connected.
     */
    'intake_binding_id'?: string | null;
}
