/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EnvironmentApiImageSettings } from './environment-api-image-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { EnvironmentLifecycleSettings } from './environment-lifecycle-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { EnvironmentNetworkSettings } from './environment-network-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { EnvironmentProvider } from './environment-provider';
// May contain unused imports in some cases
// @ts-ignore
import type { EnvironmentResourcesSettings } from './environment-resources-settings';

/**
 * Request body for replacing a server-managed environment. The path id is authoritative.
 */
export interface ReplaceEnvironmentRequest {
    'provider': EnvironmentProvider;
    /**
     * Local-provider command working directory for this environment. Docker and Daytona ignore this value.
     */
    'cwd'?: string | null;
    /**
     * Docker-only named private host profile under FABRO_HOME/codex-oauth. Mounts only pre-existing auth.json and auth.lock; cannot be combined with CODEX_AUTH_B64 or OPENAI_API_KEY. No host paths are accepted.
     */
    'codex_oauth_profile'?: string | null;
    'image': EnvironmentApiImageSettings;
    'resources': EnvironmentResourcesSettings;
    'network': EnvironmentNetworkSettings;
    'lifecycle': EnvironmentLifecycleSettings;
    'labels': { [key: string]: string; };
    'env': { [key: string]: string; };
}
