/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunIntentArgs } from './run-intent-args';
// May contain unused imports in some cases
// @ts-ignore
import type { RunTarget } from './run-target';

/**
 * A request to create, but not start, one run from an immutable workflow version and an explicit workspace target.
 */
export interface RunIntent {
    /**
     * SHA-256 identity of validated canonical workflow-version bytes. Hex input is case-insensitive; Fabro emits the canonical lowercase form.
     */
    'workflow_version_id': string;
    'target': RunTarget;
    'args': RunIntentArgs;
    /**
     * Server environment catalog ID. Omission selects `default`.
     */
    'environment_id'?: string;
    /**
     * Optional orchestration parent run ID.
     */
    'parent_id'?: string;
    /**
     * Optional explicit run title, normalized by the server.
     */
    'title'?: string;
    /**
     * Optional inline goal override.
     */
    'goal'?: string;
}
