/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunIntentArgsInputsValue } from './run-intent-args-inputs-value';

/**
 * Structured run overrides accepted by workflow-version creation.
 */
export interface RunIntentArgs {
    'model'?: string;
    /**
     * LLM provider; this does not select the sandbox environment.
     */
    'provider'?: string;
    'inputs'?: { [key: string]: RunIntentArgsInputsValue; };
    'labels'?: { [key: string]: string; };
    /**
     * Overrides `run.execution.mode`: true selects `dry_run`, false selects `normal`, and omission inherits the lower-precedence setting.
     */
    'dry_run'?: boolean;
    /**
     * Overrides `run.execution.approval`: true selects `auto`, false selects `prompt`, and omission inherits the lower-precedence setting.
     */
    'auto_approve'?: boolean;
    /**
     * Overrides `run.environment.lifecycle.preserve`; omission inherits the lower-precedence setting.
     */
    'preserve_sandbox'?: boolean;
}
