/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A TCP port a process inside a run sandbox listens on, as the sandbox driver reports it.
 */
export interface SandboxService {
    /**
     * Listening TCP port.
     */
    'port': number;
    /**
     * Local bind addresses the sandbox reports for the port.
     */
    'addresses': Array<string>;
    /**
     * The listening processes, when the sandbox can name them (`node`, or `pid=1234`). Empty when it cannot.
     */
    'processes': Array<string>;
    /**
     * Whether the provider supports an external preview URL for this port.
     */
    'preview_supported': boolean;
}
