/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * How the server launches a sandbox-driver plugin executable.
 */
export interface SandboxPluginSettings {
    /**
     * Executable path. Absent means `fabro-sandbox-<kind>` on `PATH`.
     */
    'path'?: string;
    /**
     * Pinned SHA-256 of the executable, hex.
     */
    'sha256'?: string;
    /**
     * Allow launching without a checksum.
     */
    'dev'?: boolean;
    'args'?: Array<string>;
    'env'?: { [key: string]: string; };
    'inherit_env'?: Array<string>;
}
