/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The kind of isolation a sandbox was provisioned with, as observed by the driver. Not an isolation guarantee.
 */

export const SandboxKind = {
    CONTAINER: 'container',
    VIRTUAL_MACHINE: 'virtual_machine',
    UNKNOWN: 'unknown'
} as const;

export type SandboxKind = typeof SandboxKind[keyof typeof SandboxKind];
