/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The sandbox driver\'s lifecycle state for a sandbox. The provider\'s own state string is preserved in `SandboxStatus.provider_state`. A reader must treat a value it does not know as `unknown`.
 */

export const SandboxState = {
    CREATING: 'creating',
    STARTING: 'starting',
    RUNNING: 'running',
    STOPPING: 'stopping',
    STOPPED: 'stopped',
    PAUSING: 'pausing',
    PAUSED: 'paused',
    RESUMING: 'resuming',
    ARCHIVING: 'archiving',
    ARCHIVED: 'archived',
    RESTORING: 'restoring',
    RESIZING: 'resizing',
    FORKING: 'forking',
    SNAPSHOTTING: 'snapshotting',
    DELETING: 'deleting',
    DELETED: 'deleted',
    ERROR: 'error',
    UNKNOWN: 'unknown'
} as const;

export type SandboxState = typeof SandboxState[keyof typeof SandboxState];
