/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SandboxNetworkPolicyOneOf } from './sandbox-network-policy-one-of';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxNetworkPolicyOneOf1 } from './sandbox-network-policy-one-of1';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxNetworkPolicyOneOf1DomainAllowList } from './sandbox-network-policy-one-of1-domain-allow-list';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxNetworkPolicyOneOfCidrAllowList } from './sandbox-network-policy-one-of-cidr-allow-list';

/**
 * @type SandboxNetworkPolicy
 * The network policy in force for a sandbox. A policy without parameters is its name; an allow list carries its entries.
 */
export type SandboxNetworkPolicy = SandboxNetworkPolicyOneOf | SandboxNetworkPolicyOneOf1 | string;
