/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Compute resources of a sandbox, in the units the field names give. A field is null when the provider does not report a value or applies its default.
 */
export interface SandboxResources {
    'cpu_cores'?: number | null;
    'memory_mb'?: number | null;
    'disk_mb'?: number | null;
    'gpus'?: number | null;
}
