/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SandboxKind } from './sandbox-kind';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxNetworkPolicy } from './sandbox-network-policy';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxResources } from './sandbox-resources';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxState } from './sandbox-state';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxWorkspaceOwnership } from './sandbox-workspace-ownership';

/**
 * What the sandbox driver reports about a sandbox. Only `id` and `state` are always present; every other field is null or empty when the provider does not report it.
 */
export interface SandboxStatus {
    /**
     * The provider\'s stable identifier for the sandbox.
     */
    'id': string;
    /**
     * The provider\'s display name, which is not the stable identifier.
     */
    'name'?: string | null;
    'state': SandboxState;
    /**
     * The provider\'s own state string, for display and debugging.
     */
    'provider_state'?: string;
    'error_reason'?: string | null;
    'resources'?: SandboxResources | null;
    'sandbox_kind'?: SandboxKind | null;
    /**
     * The provider region or target the sandbox runs in.
     */
    'region'?: string | null;
    /**
     * Provider-stored labels, including fabro\'s ownership labels.
     */
    'labels'?: { [key: string]: string; };
    /**
     * The image the sandbox runs, when the provider knows it (a Docker container\'s image reference).
     */
    'image'?: string | null;
    /**
     * The snapshot the sandbox was created from, when the provider knows it (a Daytona snapshot name).
     */
    'snapshot'?: string | null;
    'network'?: SandboxNetworkPolicy | null;
    'workspace_ownership'?: SandboxWorkspaceOwnership | null;
    /**
     * The provider\'s console page for the sandbox, when it has one.
     */
    'web_url'?: string | null;
    'created_at'?: string | null;
    /**
     * The provider\'s most recent activity or update timestamp for the sandbox.
     */
    'updated_at'?: string | null;
}
