/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunSandboxInstance } from './run-sandbox-instance';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxStatus } from './sandbox-status';

/**
 * The sandbox owned by a run, as fabro\'s record of it and the sandbox driver\'s status.
 */
export interface SandboxDetails {
    'sandbox': RunSandboxInstance;
    'status': SandboxStatus;
}
