/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BugsinkIntegrationSettings } from './bugsink-integration-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { GithubIntegrationSettings } from './github-integration-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { PlaneIntegrationSettings } from './plane-integration-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { SlackIntegrationSettings } from './slack-integration-settings';

export interface ServerIntegrationsSettings {
    'github': GithubIntegrationSettings;
    'slack': SlackIntegrationSettings;
    'plane': PlaneIntegrationSettings;
    'bugsink': BugsinkIntegrationSettings;
}
