/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContextWindowBreakdownItem } from './context-window-breakdown-item';
// May contain unused imports in some cases
// @ts-ignore
import type { ContextWindowCountMethod } from './context-window-count-method';
// May contain unused imports in some cases
// @ts-ignore
import type { ContextWindowStaleness } from './context-window-staleness';
// May contain unused imports in some cases
// @ts-ignore
import type { ContextWindowWarning } from './context-window-warning';
// May contain unused imports in some cases
// @ts-ignore
import type { StageContextWindowUnavailableReason } from './stage-context-window-unavailable-reason';

/**
 * Best-effort context-window usage for one agent stage.
 */
export interface StageContextWindow {
    /**
     * Stage ID in `node@visit` form.
     */
    'stage_id': string;
    /**
     * Whether context-window data is available for this known stage.
     */
    'available': boolean;
    'unavailable_reason': StageContextWindowUnavailableReason | null;
    'provider': string | null;
    'model': string | null;
    'context_window_tokens': number | null;
    'input_tokens': number | null;
    'usage_percent': number | null;
    'count_method': ContextWindowCountMethod | null;
    'staleness': ContextWindowStaleness;
    'generated_at': string | null;
    'event_seq': number | null;
    'breakdown': Array<ContextWindowBreakdownItem>;
    'warnings': Array<ContextWindowWarning>;
}
