/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Coarse tool category for display and grouping.
 */

export const ToolCategory = {
    READ: 'read',
    WRITE: 'write',
    SHELL: 'shell',
    SUBAGENT: 'subagent',
    OTHER: 'other'
} as const;

export type ToolCategory = typeof ToolCategory[keyof typeof ToolCategory];
