/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ToolSourceApplication } from './tool-source-application';
// May contain unused imports in some cases
// @ts-ignore
import type { ToolSourceMcp } from './tool-source-mcp';
// May contain unused imports in some cases
// @ts-ignore
import type { ToolSourceNative } from './tool-source-native';
// May contain unused imports in some cases
// @ts-ignore
import type { ToolSourceSkill } from './tool-source-skill';

/**
 * @type ToolSource
 * Origin of an effective agent tool.
 */
export type ToolSource = { kind: 'application' } & ToolSourceApplication | { kind: 'mcp' } & ToolSourceMcp | { kind: 'native' } & ToolSourceNative | { kind: 'skill' } & ToolSourceSkill;
