/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A tool the coding agent itself implements.
 */
export interface ToolSourceNative {
    'kind': ToolSourceNativeKindEnum;
}

export const ToolSourceNativeKindEnum = {
    NATIVE: 'native'
} as const;

export type ToolSourceNativeKindEnum = typeof ToolSourceNativeKindEnum[keyof typeof ToolSourceNativeKindEnum];
