/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Automation } from '../models';
// @ts-ignore
import type { CreateProjectAutomationRequest } from '../models';
// @ts-ignore
import type { CreateProjectRequest } from '../models';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { GithubRepositoryListResponse } from '../models';
// @ts-ignore
import type { Project } from '../models';
// @ts-ignore
import type { ProjectListResponse } from '../models';
// @ts-ignore
import type { UpdateProjectRequest } from '../models';
/**
 * ProjectsApi - axios parameter creator
 */
export const ProjectsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Connects an existing accessible GitHub repository as a Fabro project. The server re-reads repository identity and the default branch with its own server credentials; caller-supplied permission or default-branch claims are ignored. Connecting performs no clone, Plane mutation, trigger activation, or deployment.
         * @summary Connect a project
         * @param {CreateProjectRequest} createProjectRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProject: async (createProjectRequest: CreateProjectRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createProjectRequest' is not null or undefined
            assertParamExists('createProject', 'createProjectRequest', createProjectRequest)
            const localVarPath = `/api/v1/projects`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionCookie required

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createProjectRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a concrete automation instance owned by the project from a global definition marked available to projects. The instance keeps the source workflow selector and workflow source, targets the project\'s repository and default branch, and starts with every trigger disabled. Repeating the exact request returns the existing instance.
         * @summary Add an automation to a project
         * @param {string} id Unique project identifier.
         * @param {CreateProjectAutomationRequest} createProjectAutomationRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProjectAutomation: async (id: string, createProjectAutomationRequest: CreateProjectAutomationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('createProjectAutomation', 'id', id)
            // verify required parameter 'createProjectAutomationRequest' is not null or undefined
            assertParamExists('createProjectAutomation', 'createProjectAutomationRequest', createProjectAutomationRequest)
            const localVarPath = `/api/v1/projects/{id}/automations`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionCookie required

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createProjectAutomationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Enumerates repositories visible to the Fabro server\'s configured GitHub credentials. The cursor is opaque and server-issued; callers cannot supply a repository URL. A failed upstream page is never reported as an empty result.
         * @summary List repositories available to this server
         * @param {string} [cursor] Opaque cursor returned by a previous page of results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listGithubRepositories: async (cursor?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/repos/github`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionCookie required

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns every GitHub repository connected to this Fabro server.
         * @summary List projects
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listProjects: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/projects`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionCookie required

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns one connected project by id.
         * @summary Retrieve project
         * @param {string} id Unique project identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveProject: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('retrieveProject', 'id', id)
            const localVarPath = `/api/v1/projects/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionCookie required

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates the project display name when `If-Match` matches the current project revision. Repository identity and the intake binding are not mutable here.
         * @summary Update project
         * @param {string} id Unique project identifier.
         * @param {string} ifMatch Current resource revision used for optimistic concurrency, as returned in the &#x60;ETag&#x60; response header.
         * @param {UpdateProjectRequest} updateProjectRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProject: async (id: string, ifMatch: string, updateProjectRequest: UpdateProjectRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateProject', 'id', id)
            // verify required parameter 'ifMatch' is not null or undefined
            assertParamExists('updateProject', 'ifMatch', ifMatch)
            // verify required parameter 'updateProjectRequest' is not null or undefined
            assertParamExists('updateProject', 'updateProjectRequest', updateProjectRequest)
            const localVarPath = `/api/v1/projects/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SessionCookie required

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (ifMatch != null) {
                localVarHeaderParameter['If-Match'] = String(ifMatch);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateProjectRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProjectsApi - functional programming interface
 */
export const ProjectsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProjectsApiAxiosParamCreator(configuration)
    return {
        /**
         * Connects an existing accessible GitHub repository as a Fabro project. The server re-reads repository identity and the default branch with its own server credentials; caller-supplied permission or default-branch claims are ignored. Connecting performs no clone, Plane mutation, trigger activation, or deployment.
         * @summary Connect a project
         * @param {CreateProjectRequest} createProjectRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createProject(createProjectRequest: CreateProjectRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Project>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createProject(createProjectRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectsApi.createProject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Creates a concrete automation instance owned by the project from a global definition marked available to projects. The instance keeps the source workflow selector and workflow source, targets the project\'s repository and default branch, and starts with every trigger disabled. Repeating the exact request returns the existing instance.
         * @summary Add an automation to a project
         * @param {string} id Unique project identifier.
         * @param {CreateProjectAutomationRequest} createProjectAutomationRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createProjectAutomation(id: string, createProjectAutomationRequest: CreateProjectAutomationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Automation>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createProjectAutomation(id, createProjectAutomationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectsApi.createProjectAutomation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Enumerates repositories visible to the Fabro server\'s configured GitHub credentials. The cursor is opaque and server-issued; callers cannot supply a repository URL. A failed upstream page is never reported as an empty result.
         * @summary List repositories available to this server
         * @param {string} [cursor] Opaque cursor returned by a previous page of results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listGithubRepositories(cursor?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GithubRepositoryListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listGithubRepositories(cursor, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectsApi.listGithubRepositories']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns every GitHub repository connected to this Fabro server.
         * @summary List projects
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listProjects(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listProjects(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectsApi.listProjects']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns one connected project by id.
         * @summary Retrieve project
         * @param {string} id Unique project identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retrieveProject(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Project>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retrieveProject(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectsApi.retrieveProject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updates the project display name when `If-Match` matches the current project revision. Repository identity and the intake binding are not mutable here.
         * @summary Update project
         * @param {string} id Unique project identifier.
         * @param {string} ifMatch Current resource revision used for optimistic concurrency, as returned in the &#x60;ETag&#x60; response header.
         * @param {UpdateProjectRequest} updateProjectRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateProject(id: string, ifMatch: string, updateProjectRequest: UpdateProjectRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Project>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateProject(id, ifMatch, updateProjectRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectsApi.updateProject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProjectsApi - factory interface
 */
export const ProjectsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProjectsApiFp(configuration)
    return {
        /**
         * Connects an existing accessible GitHub repository as a Fabro project. The server re-reads repository identity and the default branch with its own server credentials; caller-supplied permission or default-branch claims are ignored. Connecting performs no clone, Plane mutation, trigger activation, or deployment.
         * @summary Connect a project
         * @param {CreateProjectRequest} createProjectRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProject(createProjectRequest: CreateProjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<Project> {
            return localVarFp.createProject(createProjectRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a concrete automation instance owned by the project from a global definition marked available to projects. The instance keeps the source workflow selector and workflow source, targets the project\'s repository and default branch, and starts with every trigger disabled. Repeating the exact request returns the existing instance.
         * @summary Add an automation to a project
         * @param {string} id Unique project identifier.
         * @param {CreateProjectAutomationRequest} createProjectAutomationRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProjectAutomation(id: string, createProjectAutomationRequest: CreateProjectAutomationRequest, options?: RawAxiosRequestConfig): AxiosPromise<Automation> {
            return localVarFp.createProjectAutomation(id, createProjectAutomationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Enumerates repositories visible to the Fabro server\'s configured GitHub credentials. The cursor is opaque and server-issued; callers cannot supply a repository URL. A failed upstream page is never reported as an empty result.
         * @summary List repositories available to this server
         * @param {string} [cursor] Opaque cursor returned by a previous page of results.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listGithubRepositories(cursor?: string, options?: RawAxiosRequestConfig): AxiosPromise<GithubRepositoryListResponse> {
            return localVarFp.listGithubRepositories(cursor, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns every GitHub repository connected to this Fabro server.
         * @summary List projects
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listProjects(options?: RawAxiosRequestConfig): AxiosPromise<ProjectListResponse> {
            return localVarFp.listProjects(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns one connected project by id.
         * @summary Retrieve project
         * @param {string} id Unique project identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveProject(id: string, options?: RawAxiosRequestConfig): AxiosPromise<Project> {
            return localVarFp.retrieveProject(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates the project display name when `If-Match` matches the current project revision. Repository identity and the intake binding are not mutable here.
         * @summary Update project
         * @param {string} id Unique project identifier.
         * @param {string} ifMatch Current resource revision used for optimistic concurrency, as returned in the &#x60;ETag&#x60; response header.
         * @param {UpdateProjectRequest} updateProjectRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProject(id: string, ifMatch: string, updateProjectRequest: UpdateProjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<Project> {
            return localVarFp.updateProject(id, ifMatch, updateProjectRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProjectsApi - object-oriented interface
 */
export class ProjectsApi extends BaseAPI {
    /**
     * Connects an existing accessible GitHub repository as a Fabro project. The server re-reads repository identity and the default branch with its own server credentials; caller-supplied permission or default-branch claims are ignored. Connecting performs no clone, Plane mutation, trigger activation, or deployment.
     * @summary Connect a project
     * @param {CreateProjectRequest} createProjectRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createProject(createProjectRequest: CreateProjectRequest, options?: RawAxiosRequestConfig) {
        return ProjectsApiFp(this.configuration).createProject(createProjectRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates a concrete automation instance owned by the project from a global definition marked available to projects. The instance keeps the source workflow selector and workflow source, targets the project\'s repository and default branch, and starts with every trigger disabled. Repeating the exact request returns the existing instance.
     * @summary Add an automation to a project
     * @param {string} id Unique project identifier.
     * @param {CreateProjectAutomationRequest} createProjectAutomationRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createProjectAutomation(id: string, createProjectAutomationRequest: CreateProjectAutomationRequest, options?: RawAxiosRequestConfig) {
        return ProjectsApiFp(this.configuration).createProjectAutomation(id, createProjectAutomationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Enumerates repositories visible to the Fabro server\'s configured GitHub credentials. The cursor is opaque and server-issued; callers cannot supply a repository URL. A failed upstream page is never reported as an empty result.
     * @summary List repositories available to this server
     * @param {string} [cursor] Opaque cursor returned by a previous page of results.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listGithubRepositories(cursor?: string, options?: RawAxiosRequestConfig) {
        return ProjectsApiFp(this.configuration).listGithubRepositories(cursor, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns every GitHub repository connected to this Fabro server.
     * @summary List projects
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listProjects(options?: RawAxiosRequestConfig) {
        return ProjectsApiFp(this.configuration).listProjects(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns one connected project by id.
     * @summary Retrieve project
     * @param {string} id Unique project identifier.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public retrieveProject(id: string, options?: RawAxiosRequestConfig) {
        return ProjectsApiFp(this.configuration).retrieveProject(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates the project display name when `If-Match` matches the current project revision. Repository identity and the intake binding are not mutable here.
     * @summary Update project
     * @param {string} id Unique project identifier.
     * @param {string} ifMatch Current resource revision used for optimistic concurrency, as returned in the &#x60;ETag&#x60; response header.
     * @param {UpdateProjectRequest} updateProjectRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateProject(id: string, ifMatch: string, updateProjectRequest: UpdateProjectRequest, options?: RawAxiosRequestConfig) {
        return ProjectsApiFp(this.configuration).updateProject(id, ifMatch, updateProjectRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
