CREATE TABLE automation_plane_triggers (
    automation_id TEXT NOT NULL,
    id TEXT NOT NULL,
    enabled INTEGER NOT NULL,
    project_id TEXT NOT NULL,
    ready_state_id TEXT NOT NULL,
    in_progress_state_id TEXT NOT NULL,
    done_state_id TEXT NOT NULL,
    cancelled_state_id TEXT NOT NULL,
    failure_label_id TEXT,
    default_harness TEXT NOT NULL,
    codex_label_id TEXT,
    omp_label_id TEXT,
    poll_interval_seconds INTEGER NOT NULL,
    max_concurrency INTEGER NOT NULL,
    max_retries INTEGER NOT NULL,
    PRIMARY KEY (automation_id, id),
    FOREIGN KEY (automation_id) REFERENCES automations(id) ON DELETE CASCADE,
    CHECK (length(id) BETWEEN 1 AND 63),
    CHECK (substr(id, 1, 1) GLOB '[a-z0-9]'),
    CHECK (id NOT GLOB '*[^a-z0-9_-]*'),
    CHECK (enabled IN (0, 1)),
    CHECK (length(trim(project_id)) > 0),
    CHECK (length(trim(ready_state_id)) > 0),
    CHECK (length(trim(in_progress_state_id)) > 0),
    CHECK (length(trim(done_state_id)) > 0),
    CHECK (length(trim(cancelled_state_id)) > 0),
    CHECK (default_harness IN ('codex', 'omp')),
    CHECK (poll_interval_seconds BETWEEN 15 AND 3600),
    CHECK (max_concurrency BETWEEN 1 AND 10),
    CHECK (max_retries = 1)
);

CREATE TABLE plane_dispatches (
    automation_id TEXT NOT NULL,
    trigger_id TEXT NOT NULL,
    issue_id TEXT NOT NULL,
    issue_identifier TEXT NOT NULL,
    issue_title TEXT,
    issue_url TEXT,
    status TEXT NOT NULL,
    harness TEXT NOT NULL,
    attempt INTEGER NOT NULL,
    run_ids TEXT NOT NULL,
    current_run_id TEXT,
    pull_request_url TEXT,
    last_error TEXT,
    claimed_at TEXT,
    completed_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    claimed_state_applied INTEGER NOT NULL DEFAULT 0,
    claim_comment_posted INTEGER NOT NULL DEFAULT 0,
    success_state_applied INTEGER NOT NULL DEFAULT 0,
    success_comment_posted INTEGER NOT NULL DEFAULT 0,
    failure_comment_posted INTEGER NOT NULL DEFAULT 0,
    failure_label_applied INTEGER NOT NULL DEFAULT 0,
    cancelled_state_applied INTEGER NOT NULL DEFAULT 0,
    cancelled_comment_posted INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (automation_id, trigger_id, issue_id),
    CHECK (status IN (
        'pending',
        'claimed',
        'running',
        'retry_pending',
        'succeeded',
        'failed',
        'cancelled'
    )),
    CHECK (harness IN ('codex', 'omp')),
    CHECK (attempt >= 1),
    CHECK (claimed_state_applied IN (0, 1)),
    CHECK (claim_comment_posted IN (0, 1)),
    CHECK (success_state_applied IN (0, 1)),
    CHECK (success_comment_posted IN (0, 1)),
    CHECK (failure_comment_posted IN (0, 1)),
    CHECK (failure_label_applied IN (0, 1)),
    CHECK (cancelled_state_applied IN (0, 1)),
    CHECK (cancelled_comment_posted IN (0, 1))
);

CREATE INDEX plane_dispatches_automation_updated
    ON plane_dispatches (automation_id, updated_at DESC);
